updated multiple scripts to check that requirements are installed

diff --git a/arch-wiki b/arch-wiki
--- a/arch-wiki
+++ b/arch-wiki
@@ -1,4 +1,11 @@
 #!/bin/bash
+# Requires `arch-wiki-docs`
+# Requires `fuzzel`
+
+if ! command -v $DMENU_CMD &> /dev/null; then
+    echo "Could not find dmenu-compatible launcher."
+    exit 1
+fi
 
 DMENU_CMD="fuzzel -d"
 BROWSER="xdg-open"
diff --git a/powermenu b/powermenu
--- a/powermenu
+++ b/powermenu
@@ -1,6 +1,12 @@
 #!/bin/sh
+# Requires `fuzzel`
 
 DMENU_CMD="fuzzel -d"
+
+if ! command -v $DMENU_CMD &> /dev/null; then
+    echo "Could not find dmenu-compatible launcher."
+    exit 1
+fi
 
 case $(printf "󱅞 Lock\n󰶐 Turn Off Monitors\n󰷛 Lock and Turn Off Monitors\n󰩈 Log Out\n󰒲 Suspend\n Reboot\n󰑥 Soft Reboot\n Reboot into UEFI\n Reboot into Windows\n󰐥 Shutdown" | ${DMENU_CMD}) in
     "󱅞 Lock")
diff --git a/screenshot b/screenshot
--- a/screenshot
+++ b/screenshot
@@ -1,6 +1,11 @@
 #!/bin/sh
-
 # Requires "grimblast"
+
+if ! grimblast check &> /dev/null; then
+    echo "\"grimblast\" is missing dependencies"
+    exit 1
+fi
+
 FILE="$(xdg-user-dir PICTURES)/screenshots/$(date +%Y-%m-%d_%H-%m-%s).png"
 
 help_text() {
